name: Image build and Trivy Security Scan
on:
    push:
        branches:
            - main
        paths:
            - "app/**"

    pull_request:
        branches:
            - main
        paths:
            - "app/**"

jobs:
    trivy-scan:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Build Docker Image
              run: |
                  docker build -t my-app:${{ github.sha }} ./app

            - name: Scan Docker Image
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                  image-ref: my-app:${{ github.sha }}
                  format: table
                  severity: HIGH,CRITICAL
                  exit-code: 1

            # - name: Push Docker Image to Registry
            #   if: success()  # Only push if the scan is successful
            #   run: |
            #       echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            #       docker tag my-app:${{ github.sha }} my-dockerhub-username/my-app:${{ github.sha }}
            #       docker push my-dockerhub-username/my-app:${{ github.sha }}
