name: Trivy Security Scan

on:
    push:
        branches: [/manifests/helm/**]
    pull_request:
        branches: [/manifests/]

jobs:
    trivy-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run Trivy scan
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: my-app:latest
                  format: "table"
                  exit-code: "1"
                  vuln-type: "os,library"
                  severity: "CRITICAL,HIGH"
